parameters:
    phpbb.board.announcements.tables.announcements: '%core.table_prefix%board_announcements'
    phpbb.board.announcements.tables.announcements_track: '%core.table_prefix%board_announcements_track'
